import { DatePipe } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, Component, ElementRef, HostListener, ViewChild, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize, switchMap } from 'rxjs';
import { register } from 'swiper/element/bundle';
import { Project } from '../../core/models/portfolio.models';
import { ApiService } from '../../core/services/api.service';
import { LocalComment, LocalStorageService } from '../../core/services/local-storage.service';
import { NotificationService } from '../../core/services/notification.service';
import { PortfolioStore } from '../../core/services/portfolio.store';
import { SeoService } from '../../core/services/seo.service';
import { LikeButtonComponent, ProjectCardComponent, ProjectImageComponent, StateComponent } from '../../shared/components/ui.components';

register();

@Component({selector:'app-project-detail',standalone:true,imports:[RouterLink,ReactiveFormsModule,DatePipe,LikeButtonComponent,ProjectCardComponent,ProjectImageComponent,StateComponent],schemas:[CUSTOM_ELEMENTS_SCHEMA],template:`
@if(loading()){<section class="section container"><div class="skeleton"></div></section>}@else if(error()){<section class="section container"><app-state title="Case study unavailable" [message]="error()"/></section>}@else if(project();as p){
<article><header class="project-hero section"><div class="container"><nav class="breadcrumbs"><a routerLink="/">Home</a> / <a routerLink="/projects">Projects</a> / {{p.short_title}}</nav><p class="eyebrow">{{p.category}} · {{p.year}}</p><h1>{{p.title}}</h1><p class="lead">{{p.summary}}</p><div class="hero-meta"><span><b>Status</b>{{p.status}}</span>@if(p.duration){<span><b>Duration</b>{{p.duration}}</span>}@if(p.company){<span><b>Company</b>{{p.company}}</span>}@if(p.role){<span><b>Role</b>{{p.role}}</span>}@if(p.work_mode){<span><b>Work mode</b>{{p.work_mode}}</span>}<app-like-button [slug]="p.slug"/></div></div></header>
<section class="container cover"><app-project-image [src]="coverPath(p)" [alt]="coverAlt(p)" [label]="p.short_title"/></section>
<section class="section container overview"><aside><p class="eyebrow">Technology</p><div class="chips">@for(t of p.technologies;track t){<span class="chip">{{t}}</span>}</div></aside><div><h2>Project overview</h2><p>{{p.description}}</p>@if(p.responsibilities.length){<h3>{{contributionLabel(p)}}</h3><ul>@for(item of p.responsibilities;track item){<li>{{item}}</li>}</ul>}</div></section>
<section class="section narrative"><div class="container grid-3"><div class="panel"><span>01 / Challenge</span><h2>The problem</h2>@for(item of p.challenges;track item){<p>{{item}}</p>}</div><div class="panel"><span>02 / Approach</span><h2>The solution</h2>@for(item of p.solutions;track item){<p>{{item}}</p>}</div><div class="panel"><span>03 / Result</span><h2>The outcome</h2>@for(item of p.outcomes;track item){<p>{{item}}</p>}</div></div><div class="container metrics">@for(metric of p.metrics;track metric.label){<div><strong>{{metric.value}}</strong><span>{{metric.label}}</span></div>}</div></section>
@if(p.gallery.length){<section class="section container"><p class="eyebrow">Screenshot gallery</p><div class="gallery-main"><button type="button" (click)="openLightbox()"><app-project-image [src]="galleryPath(p,activeImage())" [alt]="p.gallery[activeImage()].alt" [label]="p.short_title"/></button><p>{{p.gallery[activeImage()].caption}}</p></div>@if(p.gallery.length>1){<swiper-container class="project-swiper" slides-per-view="auto" space-between="16" keyboard="true" navigation="true" aria-label="Screenshot carousel">@for(image of p.gallery;track image.path){<swiper-slide><button type="button" [class.active]="$index===activeImage()" (click)="activeImage.set($index)"><app-project-image [src]="'/'+image.path" [alt]="image.alt" [label]="p.short_title"/><span>{{image.caption}}</span></button></swiper-slide>}</swiper-container>}</section>}
<section class="section comments"><div class="container grid-2"><div><p class="eyebrow">Local guestbook</p><h2>Leave a local comment</h2><p class="notice">Comments are stored only in this browser as an interactive portfolio demonstration.</p><form [formGroup]="commentForm" (ngSubmit)="saveComment()"><label class="form-field">Display name<input formControlName="displayName" maxlength="80"></label><label class="form-field">Comment<textarea formControlName="message" maxlength="1000" rows="5"></textarea><span class="counter">{{commentForm.controls.message.value.length}} / 1000</span></label><button class="btn" [disabled]="commentForm.invalid">{{editing()?'Save edit':'Add local comment'}}</button>@if(editing()){<button class="btn ghost" type="button" (click)="cancelEdit()">Cancel</button>}</form></div><div class="comment-list">@for(comment of comments();track comment.id){<article class="panel"><header><strong>{{comment.displayName}}</strong><time>{{comment.createdAt|date:'medium'}}</time></header><p>{{comment.message}}</p>@if(comment.editedAt){<small>Edited {{comment.editedAt|date:'short'}}</small>}<footer><button type="button" (click)="edit(comment)">Edit</button><button type="button" (click)="remove(comment.id)">Delete</button></footer></article>}@empty{<app-state title="No local comments yet" message="Add the first note stored in this browser."/>}</div></div></section>
<section class="section container feedback"><div><p class="eyebrow">Private feedback</p><h2>Send this feedback to Harsh</h2><p>Unlike local comments, this form explicitly sends an email through FastAPI.</p></div><form [formGroup]="feedbackForm" (ngSubmit)="sendFeedback()"><div class="grid-2"><label class="form-field">Name<input formControlName="name"></label><label class="form-field">Email (optional)<input formControlName="email" type="email"></label></div><label class="form-field">Feedback type<select formControlName="feedback_type"><option value="comment">Comment</option><option value="appreciation">Appreciation</option><option value="project-inquiry">Project inquiry</option></select></label><label class="form-field">Message<textarea formControlName="message" maxlength="2000" rows="5"></textarea></label><input class="honeypot" formControlName="website" tabindex="-1"><button class="btn" [disabled]="feedbackForm.invalid||sending()">{{sending()?'Sending…':'Send feedback'}}</button></form></section>
<section class="section related container"><h2>Related projects</h2><div class="grid-2">@for(item of related();track item.slug){<app-project-card [project]="item"/>}</div><nav class="project-nav">@if(previous();as prev){<a [routerLink]="['/projects',prev.slug]">← {{prev.short_title}}</a>}@if(next();as nxt){<a [routerLink]="['/projects',nxt.slug]">{{nxt.short_title}} →</a>}</nav></section></article>
@if(lightbox()&&p.gallery.length){<div class="lightbox" role="dialog" aria-modal="true" aria-label="Project screenshot" (click)="closeLightbox()"><button #closeButton type="button" (click)="closeLightbox()" aria-label="Close lightbox">×</button><div (click)="$event.stopPropagation()"><app-project-image [src]="galleryPath(p,activeImage())" [alt]="p.gallery[activeImage()].alt" [label]="p.short_title"/><p>{{p.gallery[activeImage()].caption}}</p>@if(p.gallery.length>1){<nav><button type="button" (click)="move(-1)">← Previous</button><button type="button" (click)="move(1)">Next →</button></nav>}</div></div>}}
`,styleUrl:'project-detail.component.scss'})
export class ProjectDetailComponent {
  project=signal<Project|null>(null); loading=signal(true); error=signal(''); activeImage=signal(0); lightbox=signal(false); comments=signal<LocalComment[]>([]); editing=signal<string|null>(null); sending=signal(false);
  @ViewChild('closeButton') closeButton?:ElementRef<HTMLButtonElement>;
  private focusBeforeLightbox:HTMLElement|null=null;
  commentForm=this.fb.nonNullable.group({displayName:['',[Validators.required,Validators.minLength(2),Validators.maxLength(80)]],message:['',[Validators.required,Validators.minLength(2),Validators.maxLength(1000)]]});
  feedbackForm=this.fb.nonNullable.group({name:['',[Validators.required,Validators.minLength(2)]],email:['',[Validators.email]],feedback_type:['comment' as 'comment'|'appreciation'|'project-inquiry',Validators.required],message:['',[Validators.required,Validators.minLength(10),Validators.maxLength(2000)]],website:['']});
  constructor(route:ActivatedRoute,private api:ApiService,private fb:FormBuilder,private local:LocalStorageService,private notices:NotificationService,private seo:SeoService,private store:PortfolioStore){route.paramMap.pipe(switchMap(params=>{const slug=params.get('slug');this.loading.set(true);this.error.set('');this.project.set(null);this.activeImage.set(0);if(!slug)throw new Error('Project route is missing a slug');return this.api.project(slug).pipe(finalize(()=>this.loading.set(false)))})).subscribe({next:project=>{this.project.set(project);this.comments.set(this.local.comments(project.slug));this.seo.set(project.title,project.summary,`/projects/${project.slug}`)},error:error=>{this.error.set(error?.message||'Unable to load this case study');this.loading.set(false)}})}
  private list(){return this.store.data()?.projects??[]}
  private readonly relationships:Record<string,string[]>={'amazon-q-cost-analytics-assistant':['distributed-multi-drone-ai-tracking','aws-cost-calculator'],'distributed-multi-drone-ai-tracking':['air-pollution-prediction','amazon-q-cost-analytics-assistant'],'documentation-module':['aws-native-services-platform','aws-cost-calculator'],'aws-native-services-platform':['aws-cost-calculator','amazon-q-cost-analytics-assistant'],'aws-cost-calculator':['aws-native-services-platform','amazon-q-cost-analytics-assistant'],'air-pollution-prediction':['distributed-multi-drone-ai-tracking']};
  related():Project[]{const slugs=this.relationships[this.project()?.slug||'']||[];return slugs.map(slug=>this.list().find(p=>p.slug===slug)).filter((p):p is Project=>!!p)}
  coverPath(project:Project){return project.gallery[0]?.path?`/${project.gallery[0].path}`:''}
  coverAlt(project:Project){return project.gallery[0]?.alt||`${project.title} visual fallback`}
  galleryPath(project:Project,index:number){return project.gallery[index]?.path?`/${project.gallery[index].path}`:''}
  contributionLabel(project:Project){if(project.slug==='air-pollution-prediction')return 'Project work';if(project.slug==='distributed-multi-drone-ai-tracking')return 'System responsibilities';return 'My contribution'}
  previous():Project|null{const i=this.list().findIndex(p=>p.slug===this.project()?.slug);return i>0?this.list()[i-1]:null}
  next():Project|null{const i=this.list().findIndex(p=>p.slug===this.project()?.slug);return i>=0&&i<this.list().length-1?this.list()[i+1]:null}
  saveComment(){const p=this.project();if(!p||this.commentForm.invalid)return;const v=this.commentForm.getRawValue();if(this.editing())this.local.editComment(p.slug,this.editing()!,v.message);else this.local.saveComment(p.slug,v.displayName,v.message);this.comments.set(this.local.comments(p.slug));this.commentForm.reset();this.editing.set(null);this.notices.show('Local comment saved in this browser','success')}
  edit(c:LocalComment){this.editing.set(c.id);this.commentForm.setValue({displayName:c.displayName,message:c.message})} cancelEdit(){this.editing.set(null);this.commentForm.reset()}
  remove(id:string){const p=this.project();if(p&&confirm('Delete this local comment from your browser?')){this.local.deleteComment(p.slug,id);this.comments.set(this.local.comments(p.slug))}}
  sendFeedback(){const p=this.project();if(!p||this.feedbackForm.invalid)return;this.sending.set(true);const v=this.feedbackForm.getRawValue();this.api.feedback({...v,email:v.email||null,project_slug:p.slug}).pipe(finalize(()=>this.sending.set(false))).subscribe(()=>{this.notices.show('Feedback sent to Harsh','success');this.feedbackForm.reset({feedback_type:'comment',website:''})})}
  openLightbox(){this.focusBeforeLightbox=document.activeElement as HTMLElement;this.lightbox.set(true);document.body.style.overflow='hidden';setTimeout(()=>this.closeButton?.nativeElement.focus())}
  closeLightbox(){this.lightbox.set(false);document.body.style.overflow='';setTimeout(()=>this.focusBeforeLightbox?.focus())}
  move(delta:number){const n=this.project()?.gallery.length||1;this.activeImage.update(v=>(v+delta+n)%n)}
  @HostListener('document:keydown',['$event']) keys(e:KeyboardEvent){if(!this.lightbox())return;if(e.key==='Escape')this.closeLightbox();if(e.key==='ArrowRight')this.move(1);if(e.key==='ArrowLeft')this.move(-1);if(e.key==='Tab'){const dialog=document.querySelector<HTMLElement>('.lightbox');const focusable=dialog?.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])');if(!focusable?.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
}
