import { CommonModule } from '@angular/common';
import { Component,input,output,signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideArrowUp,LucideCopy,LucideExternalLink,LucideHeart } from '@lucide/angular';
import { Project } from '../../core/models/portfolio.models';
import { LocalStorageService } from '../../core/services/local-storage.service';
import { NotificationService } from '../../core/services/notification.service';

@Component({selector:'app-section-heading',standalone:true,template:`<header class="section-heading"><span>{{eyebrow()}}</span><h2>{{title()}}</h2><p>{{description()}}</p></header>`,styles:[`.section-heading{max-width:720px;margin-bottom:var(--space-8)}span{color:var(--accent);font:600 .75rem/1 var(--font-mono);letter-spacing:.14em;text-transform:uppercase}h2{font-size:clamp(2rem,5vw,4rem);margin:.7rem 0 1rem;letter-spacing:-.04em}p{color:var(--muted);font-size:1.08rem;margin:0}`]})export class SectionHeadingComponent{eyebrow=input('');title=input.required<string>();description=input('')}

@Component({selector:'app-like-button',standalone:true,imports:[LucideHeart],template:`<button type="button" [class.liked]="liked()" (click)="toggle()" [attr.aria-pressed]="liked()"><svg lucideHeart></svg> {{liked()?'Appreciated':'Appreciate'}}</button><span class="sr-only" aria-live="polite">{{announcement()}}</span>`,styles:[`button{display:inline-flex;gap:.5rem;align-items:center;min-height:44px;border:1px solid var(--border);background:var(--surface);color:var(--text);padding:.65rem .9rem;border-radius:99px}svg{width:18px}.liked{color:#ff718a;border-color:#ff718a}.liked svg{fill:currentColor;animation:pop .3s}@keyframes pop{50%{transform:scale(1.35)}}`]})export class LikeButtonComponent{slug=input.required<string>();liked=signal(false);announcement=signal('');constructor(private storage:LocalStorageService){}ngOnInit(){this.liked.set(this.storage.liked(this.slug()))}toggle(){this.liked.set(this.storage.toggleLike(this.slug()));this.announcement.set(this.liked()?'Project appreciated locally':'Local appreciation removed')}}

@Component({selector:'app-project-image',standalone:true,imports:[CommonModule],template:`<div class="image-wrap">@if(src()&&!failed()){<img [src]="src()" [alt]="alt()" width="1200" height="750" loading="lazy" (error)="failed.set(true)">@if(!loaded()){<span class="image-loading" aria-hidden="true"></span>}}@else{<div class="fallback"><span>HV / CASE STUDY</span><strong>{{label()}}</strong><i></i><i></i><i></i></div>}</div>`,styles:[`.image-wrap{position:relative;aspect-ratio:16/10;overflow:hidden;background:linear-gradient(135deg,#101720,#172638);height:100%}.image-wrap img{width:100%;height:100%;object-fit:contain;background:#080d11}.image-loading{position:absolute;inset:0;background:linear-gradient(90deg,#101820,#17232c,#101820);background-size:200%;animation:loading 1.2s infinite;pointer-events:none}.image-wrap img:is([complete])+.image-loading{display:none}.fallback{height:100%;padding:8%;display:flex;flex-direction:column;justify-content:flex-end;background:radial-gradient(circle at 80% 15%,rgba(83,211,184,.25),transparent 35%),linear-gradient(135deg,#111820,#1b2632);color:#f5f7f8}.fallback span{font:600 .7rem var(--font-mono);color:#6ee7cd}.fallback strong{font-size:clamp(1.3rem,3vw,2.2rem);margin:.5rem 0 1.5rem}.fallback i{height:8px;background:#ffffff12;border-radius:9px;margin:.25rem;width:80%}.fallback i:last-child{width:45%}@keyframes loading{to{background-position:-200%}}`]})export class ProjectImageComponent{src=input('');alt=input('Project preview');label=input('Project');failed=signal(false);loaded=signal(true)}

@Component({selector:'app-project-card',standalone:true,imports:[RouterLink,ProjectImageComponent,LikeButtonComponent,LucideExternalLink],template:`<article class="project-card"><a [routerLink]="['/projects',project().slug]" class="visual" [attr.aria-label]="'View '+project().title"><app-project-image [src]="coverPath()" [alt]="coverAlt()" [label]="project().short_title"/></a><div class="content"><div class="meta"><span>{{project().category}}</span><span>{{project().year}}</span></div><h3><a [routerLink]="['/projects',project().slug]">{{project().title}}</a></h3><p>{{project().summary}}</p><div class="card-metrics">@for(metric of project().metrics.slice(0,2);track metric.label){<span><strong>{{metric.value}}</strong>{{metric.label}}</span>}</div><div class="chips">@for(t of project().technologies.slice(0,5);track t){<span>{{t}}</span>}</div><div class="actions"><a [routerLink]="['/projects',project().slug]">View Case Study <svg lucideExternalLink></svg></a><app-like-button [slug]="project().slug"/></div></div></article>`,styles:[`.project-card{height:100%;display:flex;flex-direction:column;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);overflow:hidden;transition:.25s}.project-card:hover{transform:translateY(-4px);border-color:var(--border-strong);box-shadow:var(--shadow)}.visual{display:block}.content{display:flex;flex:1;flex-direction:column;padding:clamp(1.2rem,3vw,2rem)}.meta,.actions{display:flex;justify-content:space-between;align-items:center;gap:1rem}.meta{font:600 .7rem var(--font-mono);color:var(--accent);text-transform:uppercase}.meta span:last-child{color:var(--muted)}h3{font-size:clamp(1.4rem,3vw,2rem);margin:.7rem 0}h3 a{color:var(--text)}p{color:var(--muted)}.card-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem;margin:1.25rem 0 0}.card-metrics span{display:flex;flex-direction:column;padding:.75rem;border:1px solid var(--border);border-radius:var(--radius);color:var(--muted);font-size:.72rem}.card-metrics strong{color:var(--text);font-size:.92rem;margin-bottom:.2rem}.chips{display:flex;flex-wrap:wrap;gap:.4rem;margin:1.25rem 0}.chips span{overflow-wrap:anywhere;font-size:.75rem;padding:.35rem .55rem;border:1px solid var(--border);border-radius:99px}.actions{margin-top:auto}.actions>a{display:flex;align-items:center;gap:.4rem;color:var(--accent);font-weight:700}.actions svg{width:16px}@media(max-width:520px){.actions{align-items:flex-start;flex-direction:column}.card-metrics{grid-template-columns:1fr}}`]})export class ProjectCardComponent{project=input.required<Project>();coverPath(){const path=this.project().gallery[0]?.path;return path?`/${path}`:''}coverAlt(){return this.project().gallery[0]?.alt||`${this.project().title} visual fallback`}}

@Component({selector:'app-state',standalone:true,template:`<div class="state"><h3>{{title()}}</h3><p>{{message()}}</p>@if(action()){<button class="btn" (click)="retry.emit()">{{action()}}</button>}</div>`,styles:[`.state{text-align:center;padding:3rem;border:1px dashed var(--border);border-radius:var(--radius-lg);color:var(--muted)}h3{color:var(--text)}`]})export class StateComponent{title=input.required<string>();message=input('');action=input('');retry=output<void>()}
@Component({selector:'app-toast',standalone:true,template:`@if(notices.notice();as notice){<div [class]="'toast '+notice.type" role="status"><span>{{notice.message}}</span><button type="button" (click)="notices.clear()" aria-label="Dismiss">×</button></div>}`,styles:[`.toast{position:fixed;z-index:1000;right:1rem;bottom:1rem;max-width:min(420px,calc(100vw - 2rem));padding:1rem 1.2rem;border:1px solid var(--border);border-left:4px solid var(--accent);border-radius:var(--radius);background:var(--surface-strong);box-shadow:var(--shadow);display:flex;gap:1rem}.error{border-left-color:#ff718a}.success{border-left-color:#6ee7a3}.toast button{background:none;border:0;color:var(--text);font-size:1.3rem}`]})export class ToastComponent{constructor(public notices:NotificationService){}}
@Component({selector:'app-back-top',standalone:true,imports:[LucideArrowUp],template:`<button type="button" (click)="top()" aria-label="Back to top"><svg lucideArrowUp></svg></button>`,styles:[`button{position:fixed;right:1rem;bottom:5.5rem;z-index:20;width:44px;height:44px;border:1px solid var(--border);border-radius:50%;background:var(--surface);color:var(--text)}svg{width:20px}`]})export class BackTopComponent{top(){scrollTo({top:0,behavior:'smooth'})}}
@Component({selector:'app-copy-button',standalone:true,imports:[LucideCopy],template:`<button type="button" (click)="copy()"><svg lucideCopy></svg>{{copied()?'Copied':'Copy'}}</button>`,styles:[`button{display:flex;gap:.4rem;align-items:center;min-height:44px}svg{width:16px}`]})export class CopyButtonComponent{text=input.required<string>();copied=signal(false);constructor(private notices:NotificationService){}async copy(){try{await navigator.clipboard.writeText(this.text());this.copied.set(true);setTimeout(()=>this.copied.set(false),1600)}catch{this.notices.show('Clipboard access was blocked. Select and copy the text manually.','error')}}}
